name: 'makem'
author: 'Akira Komamura'
description: 'Run makem'
inputs:
  min-emacs-version:
    description: The minimum Emacs version supported by the package
    required: true
  # install-nix:
  #   description: Whether to set up Nix with binary cache enabled
  #   required: false
  #   default: true
runs:
  using: composite
  steps:
  - uses: cachix/install-nix-action@v16
    with:
      extra_nix_config: |
        substituters = https://cache.nixos.org https://emacs-ci.cachix.org
        trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= emacs-ci.cachix.org-1:B5FVOrxhXXrOL0S+tQ7USrhjMT5iOPH+QN9q0NItom4=
  - name: Lint
    run: nix run github:akirak/makem.nix
    shell: bash
  - name: Compile
    run: ${{ github.action_path }}/run.bash ${{ inputs.min-emacs-version }}
    shell: bash
